### ISSUE TITLE
backpressure

### ISSUE THREAD

**Issue by paralin** [Acebond/gomux#1]
When I proposed adding siamux to libp2p the developers took issue primarily with the fact that it doesn't support per channel backpressure which causes head of line blocking.

Do you plan to handle backpressure? Thanks!

**Comment by lukechampine** [comment]
Whoa! I had no idea someone wanted to add siamux to libp2p, but that would be very cool. I only found out about this via https://github.com/golang/go/issues/21165 😅 

Did you open an issue or PR somewhere? All I can find is https://discuss.libp2p.io/t/sia-stream-multiplexer-implementation-for-go-libp2p/1689. I'm interested to know which backpressure scenarios libp2p is concerned about, and whether they could be addressed at a layer above siamux, or if the fix has to be in siamux itself.

**Comment by Acebond** [comment]
@lukechampine first I want to say that the Siamux codebase is a work of art, and the sync.Cond (which I had to learn) usage is genius. It was a pleasure reading such beautiful code.

Secondly, doesn't Siamux / gomux already address backpressure? A million goroutines could be calling (*Stream).Write(), and they all end up in (*Mux).bufferFrame() on m.bufferCond.Wait(). Assuming the first of the million writes is like 10BG of data (so simulating a head of line blocking case), since they are a maximum of 64KB payloads, doesn't the m.bufferCond.Signal() at the bottom of (*Mux).bufferFrame() release them in ordered since sync.Cond is internally a linked listed added to from Wait()?

This means each of the million writes gets to send up to a maximum of 64KB of data, then as the (*Mux).bufferFrame returns to (*Stream).Write(), if more data is needed to be sent, it goes back onto the end of the queue. Effectively providing a fair queuing for all the streams.

**Comment by paralin** [comment]
> Did you open an issue or PR somewhere? All I can find is ...

I asked on the Discord about merging it as a multiplexer.

**Comment by lukechampine** [comment]
> Doesn't Siamux / gomux already address backpressure?

Perhaps they're referring to the read side, rather than the write side. `readLoop` blocks on `(*Stream).consumeFrame`, which means that none of the other streams can "make progress" until that frame is fully consumed. For example:
```go
s, _ := m.AcceptStream()
go func() { io.CopyN(slowWriter, s, 100) }()
s, _ := m.AcceptStream()
go func() { io.CopyN(fastWriter, s, 100) }()
```
Here, we'll spend a lot of time waiting on `slowWriter` when we could be sending frames to `fastWriter`. Even worse, if the peer sends 101 bytes to the first stream, `consumeFrame` will remain blocked forever!

In practice I don't think these are huge problems. To avoid wasting time on slow writers, you can add buffering. And to avoid stalling, just make sure that you always `Close` your streams when you're done with them.

**Comment by paralin** [comment]
FYI here is the link to the discord messages: https://discord.com/channels/806902334369824788/942671304530747402/1040719931689406525

Summary at 11/11/2022 12:41 PM:

> Marco Munizaga: Cool. From a cursory look it doesn't seem like it supports flow control which is a deal breaker. Flow control allows us to provide back pressure to a peer.
> 
> Christian Stewart: It seems to do backpressure on the entire conn, not per-stream, which could be ok for some applications. Shouldn't be the default but could possibly be an option with the disclaimer about per stream flow control:

```
// readLoop handles the actual Reads from the Mux's net.Conn. It waits for a
// frame to arrive, then routes it to the appropriate Stream, creating a new
// Stream if none exists. It then waits for the frame to be fully consumed by
// the Stream before attempting to Read again.
```

> Marco Munizaga: I would be much more interested in a muxer that behaves like the QUIC muxer: https://www.rfc-editor.org/rfc/rfc9000.html#name-streams. They do flow control on the stream and connection level.

**Comment by Acebond** [comment]
> Perhaps they're referring to the read side, rather than the write side. 
Yeah ok that makes more sense. I expect doing so would incur a performance penalty, as the reads would have an extra copy(), and need to be kept on the heap, and freed by the GC. I will benchmark later this week when I get some free time. 

In terms of implementation I'd probably just use a bytes.Buffer inside the Stream, and have consumeFrame copy into that, and (*Stream).Read() pull bytes out. That'd be simply and easy.

**Comment by Acebond** [comment]
If its too significant of a performance penalty, I'm also thinking (*Mux).OpenStream() could allow for the user to specify a fixed size buffer, if any, to give more control if and when buffering is needed.

**Comment by lukechampine** [comment]
> I've [requested again](https://discord.com/channels/806902334369824788/942671304530747402/1077471827640733727) that they have another look at this.

Thanks. I'm definitely interested in whether the performance of SiaMux could be significantly improved via flow control. Looks like the libp2p people have done some benchmarking around this.

**Comment by paralin** [comment]
@lukechampine Marco replied and mentioned that the issue has been touched on in this post here.

By my understanding the problem is as you described above: Yamux has a receive / send window. The window is buffered on the receiver side. The receiver sends messages reporting when data has been read from the window. The sender will stop sending if the buffer is full on the receiver side.

This fixes the issue of when a steam reader is slow - then it won't block up the entire conn.

**Comment by Acebond** [comment]
I have added buffered reads with a receive window, and window update messages to track its size.

**Comment by paralin** [comment]
Nice, I'll adapt the go-libp2p-siamux package to use this one and test it out / benchmark.

**Comment by Acebond** [comment]
I switched my ReverseSocks5 proxy over to gomux and it passed my stress tests.
Example of switching code from yamux to gomux which may be helpful. 
https://github.com/Acebond/ReverseSocks5/commit/7a1a496855227db5d187f29afeb21d3c1112b8a2

**Comment by paralin** [comment]
Since backpressure is added I'll close this for now. Thanks @Acebond I'll try using this module in my projects soon.
